### ISSUE TITLE
Using trace id for tracking request actions

### ISSUE THREAD

**Issue by Ssstlis** [weakteam/vicly_back#41]
I suggest we should use Kleisli, ApplicativeAsk, ApplicativeLocal for contextual boundaries
Or we can use Env monad from Tofu

- [ ] Routes middleware
- [ ] Asking for context in doobie logger
- [ ] Asking for context in all logs
- [ ] Return tracing id in all case of requests
